// Code generated by zenrpc v2.2.12; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	NewsService struct{ News, GetById, Count, NewsSummaries, AddNews, Categories, AddCategory, Tags, AddTag string }
}{
	NewsService: struct{ News, GetById, Count, NewsSummaries, AddNews, Categories, AddCategory, Tags, AddTag string }{
		News:          "news",
		GetById:       "getbyid",
		Count:         "count",
		NewsSummaries: "newssummaries",
		AddNews:       "addnews",
		Categories:    "categories",
		AddCategory:   "addcategory",
		Tags:          "tags",
		AddTag:        "addtag",
	},
}

func (NewsService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"News": {
				Description: `News return list news.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "params",
						Optional: true,
						Type:     smd.Object,
						TypeName: "QueryParams",
						Properties: smd.PropertyList{
							{
								Name: "CategoryId",
								Type: smd.Integer,
							},
							{
								Name: "TagId",
								Type: smd.Integer,
							},
							{
								Name: "PageSize",
								Type: smd.Integer,
							},
							{
								Name: "Page",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]News",
					Items: map[string]string{
						"$ref": "#/definitions/News",
					},
					Definitions: map[string]smd.Definition{
						"News": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "newsID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name:     "content",
									Optional: true,
									Type:     smd.String,
								},
								{
									Name: "author",
									Type: smd.String,
								},
								{
									Name:     "category",
									Optional: true,
									Ref:      "#/definitions/Category",
									Type:     smd.Object,
								},
								{
									Name: "tagIds",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/Tag",
									},
								},
								{
									Name: "publishedAt",
									Type: smd.String,
								},
							},
						},
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"GetById": {
				Description: `GetById returns news by ID.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "id",
						Description: `news id`,
						Type:        smd.Integer,
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "News",
					Properties: smd.PropertyList{
						{
							Name: "newsID",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name:     "content",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "author",
							Type: smd.String,
						},
						{
							Name:     "category",
							Optional: true,
							Ref:      "#/definitions/Category",
							Type:     smd.Object,
						},
						{
							Name: "tagIds",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/Tag",
							},
						},
						{
							Name: "publishedAt",
							Type: smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"Count": {
				Description: `Count returns count news by filters.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "params",
						Optional: true,
						Type:     smd.Object,
						TypeName: "QueryParams",
						Properties: smd.PropertyList{
							{
								Name: "CategoryId",
								Type: smd.Integer,
							},
							{
								Name: "TagId",
								Type: smd.Integer,
							},
							{
								Name: "PageSize",
								Type: smd.Integer,
							},
							{
								Name: "Page",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type: smd.Integer,
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"NewsSummaries": {
				Description: `NewsSummaries returns news summary by filters.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "params",
						Optional: true,
						Type:     smd.Object,
						TypeName: "QueryParams",
						Properties: smd.PropertyList{
							{
								Name: "CategoryId",
								Type: smd.Integer,
							},
							{
								Name: "TagId",
								Type: smd.Integer,
							},
							{
								Name: "PageSize",
								Type: smd.Integer,
							},
							{
								Name: "Page",
								Type: smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]NewsSummary",
					Items: map[string]string{
						"$ref": "#/definitions/NewsSummary",
					},
					Definitions: map[string]smd.Definition{
						"NewsSummary": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "newsSummaryID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "publishedAt",
									Type: smd.String,
								},
								{
									Name:     "category",
									Optional: true,
									Ref:      "#/definitions/Category",
									Type:     smd.Object,
								},
								{
									Name: "tagIds",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/Tag",
									},
								},
							},
						},
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"AddNews": {
				Description: `AddNews return new news.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "in",
						Type:     smd.Object,
						TypeName: "NewsInput",
						Properties: smd.PropertyList{
							{
								Name: "title",
								Type: smd.String,
							},
							{
								Name:     "content",
								Optional: true,
								Type:     smd.String,
							},
							{
								Name: "author",
								Type: smd.String,
							},
							{
								Name: "categoryID",
								Type: smd.Integer,
							},
							{
								Name: "tagIds",
								Type: smd.Array,
								Items: map[string]string{
									"type": smd.Integer,
								},
							},
							{
								Name:     "publishedAt",
								Optional: true,
								Type:     smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "News",
					Properties: smd.PropertyList{
						{
							Name: "newsID",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
						{
							Name:     "content",
							Optional: true,
							Type:     smd.String,
						},
						{
							Name: "author",
							Type: smd.String,
						},
						{
							Name:     "category",
							Optional: true,
							Ref:      "#/definitions/Category",
							Type:     smd.Object,
						},
						{
							Name: "tagIds",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/Tag",
							},
						},
						{
							Name: "publishedAt",
							Type: smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"Categories": {
				Description: `Categories return list category`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]Category",
					Items: map[string]string{
						"$ref": "#/definitions/Category",
					},
					Definitions: map[string]smd.Definition{
						"Category": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "categoryId",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"AddCategory": {
				Description: `AddCategory return new category.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "in",
						Type:     smd.Object,
						TypeName: "CategoryInput",
						Properties: smd.PropertyList{
							{
								Name: "title",
								Type: smd.String,
							},
							{
								Name:     "orderNumber",
								Optional: true,
								Type:     smd.Integer,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "Category",
					Properties: smd.PropertyList{
						{
							Name: "categoryId",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"Tags": {
				Description: `Tags return list tag.`,
				Parameters:  []smd.JSONSchema{},
				Returns: smd.JSONSchema{
					Type:     smd.Array,
					TypeName: "[]Tag",
					Items: map[string]string{
						"$ref": "#/definitions/Tag",
					},
					Definitions: map[string]smd.Definition{
						"Tag": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "tagID",
									Type: smd.Integer,
								},
								{
									Name: "title",
									Type: smd.String,
								},
							},
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
			"AddTag": {
				Description: `AddTag return new tag.`,
				Parameters: []smd.JSONSchema{
					{
						Name:     "in",
						Type:     smd.Object,
						TypeName: "TagInput",
						Properties: smd.PropertyList{
							{
								Name: "title",
								Type: smd.String,
							},
						},
					},
				},
				Returns: smd.JSONSchema{
					Optional: true,
					Type:     smd.Object,
					TypeName: "Tag",
					Properties: smd.PropertyList{
						{
							Name: "tagID",
							Type: smd.Integer,
						},
						{
							Name: "title",
							Type: smd.String,
						},
					},
				},
				Errors: map[int]string{
					404: "not found",
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s NewsService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.NewsService.News:
		var args = struct {
			Params *queryParams `json:"params"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"params"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.News(ctx, args.Params))

	case RPC.NewsService.GetById:
		var args = struct {
			Id int `json:"id"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"id"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.GetById(ctx, args.Id))

	case RPC.NewsService.Count:
		var args = struct {
			Params *queryParams `json:"params"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"params"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Count(ctx, args.Params))

	case RPC.NewsService.NewsSummaries:
		var args = struct {
			Params *queryParams `json:"params"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"params"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.NewsSummaries(ctx, args.Params))

	case RPC.NewsService.AddNews:
		var args = struct {
			In NewsInput `json:"in"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"in"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.AddNews(ctx, args.In))

	case RPC.NewsService.Categories:
		resp.Set(s.Categories(ctx))

	case RPC.NewsService.AddCategory:
		var args = struct {
			In CategoryInput `json:"in"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"in"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.AddCategory(ctx, args.In))

	case RPC.NewsService.Tags:
		resp.Set(s.Tags(ctx))

	case RPC.NewsService.AddTag:
		var args = struct {
			In TagInput `json:"in"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"in"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.AddTag(ctx, args.In))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
