[server]
host = "localhost"
port = "8085"
read_timeout = "30s"
write_timeout = "30s"
shutdown_timeout = "10s"

[database]
host = "localhost"
port = "5432"
dbName = "postgres"
sslMode = "disable"
max_open_cons = 25
max_idle_cons = 5
conn_max_lifetime = "5m"
