[Server]
Host = "localhost"
Port = "8085"
ReadTimeout = "30s"
WriteTimeout = "30s"
ShutdownTimeout = "10s"

[Database]
Host = "localhost"
Port = "5432"
DBName = "postgres"
SSLMode = "disable"
MaxOpenCons = 25
MaxIdleCons = 5
ConnMaxLifetime = "5m"
