[server]
host = "localhost"
port = "8080"
read_timeout = "30s"
write_timeout = "30s"
shutdown_timeout = "10s"

[database]
host = "localhost"
port = "5432"
dbName = "newsportal"
sslMode = "disable"
max_open_conns = 25
max_idle_conns = 5
conn_max_lifetime = "5m"
