-- =============================================================================
-- Diagram Name: Noname1
-- Created on: 28.09.2025 14:56:44
-- Diagram Version:
-- =============================================================================


CREATE TABLE "statuses" (
    "statusId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    PRIMARY KEY("statusId")
);

CREATE TABLE "news" (
    "newsId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "content" text,
    "author" varchar(255) NOT NULL,
    "categoryId" int4 NOT NULL,
    "tagIds" int4[],
    "createdAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "publishedAt" timestamp with time zone NOT NULL,
    "statusId" int4 NOT NULL,
    PRIMARY KEY("newsId")
);

CREATE TABLE "categories" (
    "categoryId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "orderNumber" int4,
    "statusId" int4 NOT NULL,
    PRIMARY KEY("categoryId")
);

CREATE TABLE "tags" (
    "tagId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "statusId" int4 NOT NULL,
    PRIMARY KEY("tagId")
);


ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_categories" FOREIGN KEY ("categoryId")
    REFERENCES "categories"("categoryId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "categories" ADD CONSTRAINT "Ref_categories_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;

ALTER TABLE "tags" ADD CONSTRAINT "Ref_tags_to_statuses" FOREIGN KEY ("statusId")
    REFERENCES "statuses"("statusId")
    MATCH SIMPLE
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
    NOT DEFERRABLE;
